security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
                # if you're using multiple entity managers
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/google_login
            stateless: true
            anonymous: true
        api:
                          pattern:   ^/api
                          stateless: true
                          guard:
                              authenticators:
                                  - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/api/aws_as_sns, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/google_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }